name: Workflow for run python file
on: push

jobs:

  Hello:
  runs-on: ubuntu-latest
  steps:
  - name: clone repo
    uses: actions/checkout@v4

  - name: setup python
    uses: action/setup-python@v5
    with:
      python-version: '3.10'
    
  - name: run python script
    runs: python file_1.py
