name: Send mail
on: push
jobs:
    mail:
        runs-on: ubuntu-latest
        steps:
        - name: Send email
          uses: devellany/send-mailer@v1.0.2
          if: always()
          with:
            host: smtp.google.com
            port: 465
            account: ${{secrets.ACCOUNT}}
            password: ${{secrets.MAIL_PASSWORD}}
            sender: Vishal
            from: ${{secrets.MAIL_ADDRESS}}
            to: svishalsakthivel@yahoo.com
            subject: mail title.
            body: your messages.
