name: Send mail
on: push
jobs:
    mail:
      runs-on: ubuntu-latest
      steps:
      - name: Send email
        if: ${{ always() }}
        uses: devellany/send-mail@v1.0.2
        with:
            host: smtp.google.com
            port: 465
            account: ${{secrets.ACCOUNT}}
            password: ${{secrets.MAIL_PASSWORD}}
            sender: Vishal S
            from: ${{secrets.MAIL_ADDRESS}}
            to: svishalsakthivel@yahoo.com
            subject: mail title.
            body: your messages.
