name: Send mail
on: push
jobs:
  mail:
    runs-on: ubuntu-latest
    steps:
      - uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.google.com
          # Optional port (defaults to 465)
          port: 465
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: devellany
          from: ${{secrets.MAIL_ADDRESS}}
          to: svishalsakthivel@yahoo.com
          subject: Git action Practise
          body: This is a trail mail to know about yml working in github Action.
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"README.md"}]'
